# Docker-compose file for DVH-Analytics
# http://dvh-analytics.com
# Created on Sun Jul 15 2018
# @author: Dan Cutright, PhD
# This docker-compose file runs the main, admin, and settings web servers as well as a SQL DB

version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ~/DVH-Analytics/pgsql/:/var/lib/postgresql/data

  main:
    image: dvh-analytics:latest
    ports:
      - 5006:5006
    volumes:
      - ~/DVH-Analytics/dicom/:/dicom/
    tty: true
    depends_on:
      - db

  admin:
    image: dvh-analytics:latest
    command: dvh admin --allow-websocket-origin=localhost:5007 --port=5007 --bypass-sql-test
    ports:
      - 5007:5007
    volumes:
      - ~/DVH-Analytics/dicom/:/dicom/
      - ~/DVH-Analytics/pgsql_backups:/usr/local/lib/python2.7/dist-packages/dvh/backups
    tty: true
    depends_on:
      - db

  settings:
    image: dvh-analytics:latest
    command: dvh settings --allow-websocket-origin=localhost:5008 --port=5008
    ports:
      - 5008:5008
    volumes:
      - ~/DVH-Analytics/dicom/:/dicom/
    tty: true
    depends_on:
      - db
