# Docker-compose file for DVH-Analytics
# http://dvh-analytics.com
# Created on Sun Jul 15 2018
# @author: Dan Cutright, PhD
# This docker-compose file runs a SQL DB, main/admin/settings web servers, and two DICOM listeners

version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dvh
    volumes:
      - ~/DVH-Analytics/pgsql/:/var/lib/postgresql/data

  main:
    image: dvh-analytics:latest
    ports:
      - 5006:5106
    depends_on:
      - db
    volumes:
      - ~/DVH-Analytics/dicom/:/dicom/
    tty: true

  admin:
    image: dvh-analytics:latest
    entrypoint: /admin.sh
    ports:
      - 5007:5107
    depends_on:
      - db
    volumes:
      - ~/DVH-Analytics/dicom/:/dicom/
    tty: true

  settings:
    image: dvh-analytics:latest
    entrypoint: /settings.sh
    ports:
      - 5008:5108
    depends_on:
      - db
    tty: true
